all : tableauEtBoucles
tableauEtBoucles : tableauEtBoucles.o
						gcc tableauEtBoucles.o -o tableauEtBoucles

tableauEtBoucles.o : tableauEtBoucles.c
						gcc -c tableauEtBoucles.c -o tableauEtBoucles.o
clean :
						rm -f tableauEtBoucles *.o						